name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        if $ {{ github.event.head_commit.message != '#skip' }}
        run:
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
      - name: commits
        if $ {{ github.event.head_commit.message != '#skip' }}
        run:
          env:
            COMMITS: ${{ toJson(github.event.commits) }}
          run: echo "$COMMITS"
      - name: commit messages
        if $ {{ github.event.head_commit.message != '#skip' }}
        run:
          env:
            COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          run: echo "$COMMIT_MESSAGES"
